import React from "react";
import Head from "next/head";

type LayoutProps = {
    title?: string
    children: React.ReactNode
};

export default function HomeLayout({ title, children }: LayoutProps) {
    return <>
    <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <script src="https://identity.netlify.com/v1/netlify-identity-widget.js" async></script>
        </Head>
        <main>
            {children}
        </main>
        <footer className="h-2">
            {/* By <a href="Aligator.ir">Aligator</a> */}
        </footer>
    </>;
};

/*

        
*/
