import React from "react";
import { Layout } from "antd";
import Head from "next/head";

type LayoutProps = {
    title?: string
    children: React.ReactNode
};

export default function HomeLayout({ title, children }: LayoutProps) {
    return <>
    <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
        <main>
            {children}
        </main>
        <footer>
            By <a href="Aligator.ir">Aligator</a>
        </footer>
        </Layout>
    </>;
};

/*

        
*/
