import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GetStaticPaths , GetStaticProps, GetStaticPropsContext} from 'next';

//const show = dynamic(() => import('../content/shows/yuri-on-ice.json'));

type ShowType = 'Anime' | 'Show';

type Show = {
  slug: string,
  name: string,
  type: ShowType,
  episodeCount: number,
  episodeLength: number,
  score: number,
  createdAt: Date,
  updatedAt: Date,
}

export default function Home({ ...props }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{JSON.stringify(props)}</h1>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export function getStaticProps(context: GetStaticPropsContext) : GetStaticProps<string[]> {
  //const { postname } = ctx.params

  //const content = await import(`../../posts/${postname}.md`)
  //const config = await import(`../../siteconfig.json`)
  //const data = matter(content.default)

  return {
    props: ['a','b'],
  }
}

export function getStaticPaths() : GetStaticPaths {

  const contentContext = require.context('content/shows', false, /\.json$/);
  const paths = contentContext.keys();

  return { 
    paths,
    fallback: false
   };
}