import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { GetStaticProps} from 'next';
import { getShows, Show } from 'lib/Show';

type HomePageProps = {
  data: Show[],
}

export default function Home({data} : HomePageProps) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>{JSON.stringify(data)}</p>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export const getStaticProps : GetStaticProps<HomePageProps> = async (context) => {
  const shows = await getShows();
  return {
    props: {data: shows},
  }
}